# fly.toml file generated for getyourtravel on 2023-04-06T09:37:54+02:00

app = "getyourtravel"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[env]
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED = "false"
  SPRING_DATASOURCE_URL = "jdbc:postgresql://get-your-travel-app-db.internal:5432/postgres?currentSchema=public&user=postgres&password=ZuiOSM94ugU4R68"
  SPRING_DATASOURCE_USERNAME = "postgres"
  _JAVA_OPTIONS = "-XX:MaxRAM=70m"

[experimental]
  auto_rollback = true

[mounts]
  destination = "/app/public/uploads"
  source = "getyourtravel_data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public/uploads"
  url_prefix = "/uploads"
